import Head from 'next/head'
//components
import styled from 'styled-components'
import Sidebar from '../components/sidebar/Sidebar'
import Welcome from '../components/welcome-page/Welcome'
//import Welcome from '../components/welcome-page/Welcome

export default function Home () {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container>
        <Sidebar />
        <Welcome />
      </Container>
    </div>
  )
}

const Container = styled.div`
  display: flex;
`
